name: بناء مستر كاش APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: تجهيز Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: فك مشروع مستر كاش
        run: |
          mkdir project
          ZIP_FILE=$(find . -maxdepth 1 -type f -name "*.zip" | head -n 1)
          unzip -q "$ZIP_FILE" -d project

      - name: تجهيز Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: بناء APK
        run: |
          gradle -p project assembleDebug

      - name: حفظ APK
        uses: actions/upload-artifact@v4
        with:
          name: MisterCash-APK
          path: project/app/build/outputs/apk/debug/app-debug.apk
